# Generated by Django 5.0.1 on 2026-01-23 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fraud', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_id', models.CharField(max_length=100, unique=True)),
                ('investigation_type', models.CharField(max_length=100)),
                ('findings', models.TextField()),
                ('evidence_collected', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('fraud_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forensic_investigations', to='fraud.fraudcase')),
                ('investigator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forensic_investigations',
                'ordering': ['-started_at'],
            },
        ),
    ]
